### ISSUE TITLE
Reduce size of database state file

### ISSUE THREAD

**Issue by olsonadr** [olsonadr/nlp-lambdas#4]
To enable GH tracking of incident_cls.pt, we need to decrease it's size significantly. It seems like we're doing this by pre-meaning the cls embeddings for each incident ID.

**Comment by olsonadr** [comment]
This should also include switching the formatting of this state from a torch.Tensor of shape NxMx768 for N incident_ids, M incident_reports per id, and 768 values in the CLS for each report, to <ID(1), N_INC(1), MEAN_CLS(768)>(~150)

**Comment by broceni** [comment]
We might want to add to this issue the requirement that we remove mean-ing from runtime calculations of the cosine similarity.
