### ISSUE TITLE
Testing suite

### ISSUE THREAD

**Issue by olsonadr** [olsonadr/nlp-lambdas#5]
We need to create a testing suite and pipeline for the project, likely using GitHub Actions

**Comment by broceni** [comment]
We will need issue #2 to be begun to allow the testing suite to be hooked up into it

**Comment by olsonadr** [comment]
> We will need issue #2 to be begun to allow the testing suite to be hooked up into it

#2 closed

**Comment by olsonadr** [comment]
Also we should hook this into a combined workflow pipeline with deployment, and add testing info to our documentation before closing this
