### ISSUE TITLE
Update Readme for Version 0 Changes

### ISSUE THREAD

**Issue by broceni** [olsonadr/nlp-lambdas#8]
Will need to update Readme for Version 0 Changes after the changes have been made, especially to the file structure and Deploying the example application sections.

**Comment by broceni** [comment]
Remove amazon copyright headers

**Comment by olsonadr** [comment]
- [x] DB state file
- [x] longformer submodule
- [x] aws secrets
- [x] action for deployment
- [x] new planned stuff (auto update db state, testing suite)
- [x] reword phrasing if old
- [x] remove scratch repo wording
- [x] remove incorrect amazon copyright stuff
- [ ] how to delete aws stack
- [ ] sam testing commands
